### ISSUE TITLE
Discrèétly Republish the Seized "NowTv-Drm-Key-Solution"?

### ISSUE THREAD

**Issue by Windows81** [TAJLNsScripts/filmin.es-Downloader#1]
If [that's](https://github.com/github/dmca/blob/40b3202602d1cfd07182f4e73dee18be67a03e93/2023/07/2023-07-24-sky-uk-limited.md) possible.  No pressure!

**Comment by TAJLNsScripts** [comment]
its still on my gitlab account https://gitlab.com/TAJLNsScripts

**Comment by invisiblecoder99** [comment]
https://gitlab.com/TAJLNsScripts its blocked do you have telegram ???

**Comment by TAJLNsScripts** [comment]
I probably have an account somewhere, but I don't like telegram and would prefer to not have it installed, idk why people use it. As for the script, search for it here: https://github.com/topics/nowtv and there is probably gonna be some repost

**Comment by Windows81** [comment]
I feel bad that I led them to you.

**Comment by TAJLNsScripts** [comment]
its ok

**Comment by Windows81** [comment]
I looked just today and didn't find anything relevant, unfortunately.
